//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doppler.BillingUser.ExternalServices.E4
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/", ConfigurationName="E4.ServiceSoap")]
    public interface ServiceSoap
    {

        [System.ServiceModel.OperationContractAttribute(Action="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/SendAndCommit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<E4.SendAndCommitResponse> SendAndCommitAsync(E4.SendAndCommitRequest request);

        [System.ServiceModel.OperationContractAttribute(Action="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/SendAndCommitCheck", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<E4.SendAndCommitCheckResponse> SendAndCommitCheckAsync(E4.SendAndCommitCheckRequest request);

        [System.ServiceModel.OperationContractAttribute(Action="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/TransactionInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<E4.TransactionInfoResponse> TransactionInfoAsync(E4.TransactionInfoRequest request);

        [System.ServiceModel.OperationContractAttribute(Action="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/CheckTransactionInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<E4.CheckTransactionInfoResponse> CheckTransactionInfoAsync(E4.CheckTransactionInfoRequest request);
    }

    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TransactionResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/encodedTypes")]
    public partial class Transaction
    {

        private string exactIDField;

        private string passwordField;

        private string transaction_TypeField;

        private string dollarAmountField;

        private string surchargeAmountField;

        private string card_NumberField;

        private string transaction_TagField;

        private string splitTenderIDField;

        private string track1Field;

        private string track2Field;

        private string pANField;

        private string authorization_NumField;

        private string expiry_DateField;

        private string cardHoldersNameField;

        private string cVDCodeField;

        private string cVD_Presence_IndField;

        private string zipCodeField;

        private string tax1AmountField;

        private string tax1NumberField;

        private string tax2AmountField;

        private string tax2NumberField;

        private string ecommerce_FlagField;

        private string xIDField;

        private string cAVVField;

        private string reference_NoField;

        private string customer_RefField;

        private string reference_3Field;

        private string languageField;

        private string client_IPField;

        private string client_EmailField;

        private string user_NameField;

        private string currencyField;

        private bool partialRedemptionField;

        private bool partialRedemptionFieldSpecified;

        private Level3_Type level3Field;

        private string transarmorTokenField;

        private string cardTypeField;

        private string aFTTransferTypeField;

        private string eANField;

        private bool virtualCardField;

        private bool virtualCardFieldSpecified;

        private string cardCostField;

        private string fraudSuspectedField;

        private PaypalTransactionDetails paypalResponseField;

        private SoftDescriptor_Type softDescriptorField;

        private Address_Type addressField;

        private string tPPIDField;

        private string splitShipmentNumberField;

        private string amexFraudField;

        private DynamicCurrency dynamicCurrencyField;

        private DynamicPricing dynamicPricingField;

        private string feeAmountField;

        private VisaCheckout visaCheckoutField;

        private string postDateField;

        private string otherAmountField;

        private string giftDepositAvailableField;

        private string specialPaymentField;

        private string walletProviderIDField;

        private MasterPass masterPassField;

        private string fraudDetectInAuthTransIdField;

        private string sCVField;

        private StoredCredentialsType storedCredentialsField;

        private Extra_Type[] extraField;

        /// <remarks/>
        public string ExactID
        {
            get
            {
                return this.exactIDField;
            }
            set
            {
                this.exactIDField = value;
            }
        }

        /// <remarks/>
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        public string Transaction_Type
        {
            get
            {
                return this.transaction_TypeField;
            }
            set
            {
                this.transaction_TypeField = value;
            }
        }

        /// <remarks/>
        public string DollarAmount
        {
            get
            {
                return this.dollarAmountField;
            }
            set
            {
                this.dollarAmountField = value;
            }
        }

        /// <remarks/>
        public string SurchargeAmount
        {
            get
            {
                return this.surchargeAmountField;
            }
            set
            {
                this.surchargeAmountField = value;
            }
        }

        /// <remarks/>
        public string Card_Number
        {
            get
            {
                return this.card_NumberField;
            }
            set
            {
                this.card_NumberField = value;
            }
        }

        /// <remarks/>
        public string Transaction_Tag
        {
            get
            {
                return this.transaction_TagField;
            }
            set
            {
                this.transaction_TagField = value;
            }
        }

        /// <remarks/>
        public string SplitTenderID
        {
            get
            {
                return this.splitTenderIDField;
            }
            set
            {
                this.splitTenderIDField = value;
            }
        }

        /// <remarks/>
        public string Track1
        {
            get
            {
                return this.track1Field;
            }
            set
            {
                this.track1Field = value;
            }
        }

        /// <remarks/>
        public string Track2
        {
            get
            {
                return this.track2Field;
            }
            set
            {
                this.track2Field = value;
            }
        }

        /// <remarks/>
        public string PAN
        {
            get
            {
                return this.pANField;
            }
            set
            {
                this.pANField = value;
            }
        }

        /// <remarks/>
        public string Authorization_Num
        {
            get
            {
                return this.authorization_NumField;
            }
            set
            {
                this.authorization_NumField = value;
            }
        }

        /// <remarks/>
        public string Expiry_Date
        {
            get
            {
                return this.expiry_DateField;
            }
            set
            {
                this.expiry_DateField = value;
            }
        }

        /// <remarks/>
        public string CardHoldersName
        {
            get
            {
                return this.cardHoldersNameField;
            }
            set
            {
                this.cardHoldersNameField = value;
            }
        }

        /// <remarks/>
        public string CVDCode
        {
            get
            {
                return this.cVDCodeField;
            }
            set
            {
                this.cVDCodeField = value;
            }
        }

        /// <remarks/>
        public string CVD_Presence_Ind
        {
            get
            {
                return this.cVD_Presence_IndField;
            }
            set
            {
                this.cVD_Presence_IndField = value;
            }
        }

        /// <remarks/>
        public string ZipCode
        {
            get
            {
                return this.zipCodeField;
            }
            set
            {
                this.zipCodeField = value;
            }
        }

        /// <remarks/>
        public string Tax1Amount
        {
            get
            {
                return this.tax1AmountField;
            }
            set
            {
                this.tax1AmountField = value;
            }
        }

        /// <remarks/>
        public string Tax1Number
        {
            get
            {
                return this.tax1NumberField;
            }
            set
            {
                this.tax1NumberField = value;
            }
        }

        /// <remarks/>
        public string Tax2Amount
        {
            get
            {
                return this.tax2AmountField;
            }
            set
            {
                this.tax2AmountField = value;
            }
        }

        /// <remarks/>
        public string Tax2Number
        {
            get
            {
                return this.tax2NumberField;
            }
            set
            {
                this.tax2NumberField = value;
            }
        }

        /// <remarks/>
        public string Ecommerce_Flag
        {
            get
            {
                return this.ecommerce_FlagField;
            }
            set
            {
                this.ecommerce_FlagField = value;
            }
        }

        /// <remarks/>
        public string XID
        {
            get
            {
                return this.xIDField;
            }
            set
            {
                this.xIDField = value;
            }
        }

        /// <remarks/>
        public string CAVV
        {
            get
            {
                return this.cAVVField;
            }
            set
            {
                this.cAVVField = value;
            }
        }

        /// <remarks/>
        public string Reference_No
        {
            get
            {
                return this.reference_NoField;
            }
            set
            {
                this.reference_NoField = value;
            }
        }

        /// <remarks/>
        public string Customer_Ref
        {
            get
            {
                return this.customer_RefField;
            }
            set
            {
                this.customer_RefField = value;
            }
        }

        /// <remarks/>
        public string Reference_3
        {
            get
            {
                return this.reference_3Field;
            }
            set
            {
                this.reference_3Field = value;
            }
        }

        /// <remarks/>
        public string Language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }

        /// <remarks/>
        public string Client_IP
        {
            get
            {
                return this.client_IPField;
            }
            set
            {
                this.client_IPField = value;
            }
        }

        /// <remarks/>
        public string Client_Email
        {
            get
            {
                return this.client_EmailField;
            }
            set
            {
                this.client_EmailField = value;
            }
        }

        /// <remarks/>
        public string User_Name
        {
            get
            {
                return this.user_NameField;
            }
            set
            {
                this.user_NameField = value;
            }
        }

        /// <remarks/>
        public string Currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }

        /// <remarks/>
        public bool PartialRedemption
        {
            get
            {
                return this.partialRedemptionField;
            }
            set
            {
                this.partialRedemptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool PartialRedemptionSpecified
        {
            get
            {
                return this.partialRedemptionFieldSpecified;
            }
            set
            {
                this.partialRedemptionFieldSpecified = value;
            }
        }

        /// <remarks/>
        public Level3_Type Level3
        {
            get
            {
                return this.level3Field;
            }
            set
            {
                this.level3Field = value;
            }
        }

        /// <remarks/>
        public string TransarmorToken
        {
            get
            {
                return this.transarmorTokenField;
            }
            set
            {
                this.transarmorTokenField = value;
            }
        }

        /// <remarks/>
        public string CardType
        {
            get
            {
                return this.cardTypeField;
            }
            set
            {
                this.cardTypeField = value;
            }
        }

        /// <remarks/>
        public string AFTTransferType
        {
            get
            {
                return this.aFTTransferTypeField;
            }
            set
            {
                this.aFTTransferTypeField = value;
            }
        }

        /// <remarks/>
        public string EAN
        {
            get
            {
                return this.eANField;
            }
            set
            {
                this.eANField = value;
            }
        }

        /// <remarks/>
        public bool VirtualCard
        {
            get
            {
                return this.virtualCardField;
            }
            set
            {
                this.virtualCardField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool VirtualCardSpecified
        {
            get
            {
                return this.virtualCardFieldSpecified;
            }
            set
            {
                this.virtualCardFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string CardCost
        {
            get
            {
                return this.cardCostField;
            }
            set
            {
                this.cardCostField = value;
            }
        }

        /// <remarks/>
        public string FraudSuspected
        {
            get
            {
                return this.fraudSuspectedField;
            }
            set
            {
                this.fraudSuspectedField = value;
            }
        }

        /// <remarks/>
        public PaypalTransactionDetails PaypalResponse
        {
            get
            {
                return this.paypalResponseField;
            }
            set
            {
                this.paypalResponseField = value;
            }
        }

        /// <remarks/>
        public SoftDescriptor_Type SoftDescriptor
        {
            get
            {
                return this.softDescriptorField;
            }
            set
            {
                this.softDescriptorField = value;
            }
        }

        /// <remarks/>
        public Address_Type Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        /// <remarks/>
        public string TPPID
        {
            get
            {
                return this.tPPIDField;
            }
            set
            {
                this.tPPIDField = value;
            }
        }

        /// <remarks/>
        public string SplitShipmentNumber
        {
            get
            {
                return this.splitShipmentNumberField;
            }
            set
            {
                this.splitShipmentNumberField = value;
            }
        }

        /// <remarks/>
        public string AmexFraud
        {
            get
            {
                return this.amexFraudField;
            }
            set
            {
                this.amexFraudField = value;
            }
        }

        /// <remarks/>
        public DynamicCurrency DynamicCurrency
        {
            get
            {
                return this.dynamicCurrencyField;
            }
            set
            {
                this.dynamicCurrencyField = value;
            }
        }

        /// <remarks/>
        public DynamicPricing DynamicPricing
        {
            get
            {
                return this.dynamicPricingField;
            }
            set
            {
                this.dynamicPricingField = value;
            }
        }

        /// <remarks/>
        public string FeeAmount
        {
            get
            {
                return this.feeAmountField;
            }
            set
            {
                this.feeAmountField = value;
            }
        }

        /// <remarks/>
        public VisaCheckout VisaCheckout
        {
            get
            {
                return this.visaCheckoutField;
            }
            set
            {
                this.visaCheckoutField = value;
            }
        }

        /// <remarks/>
        public string PostDate
        {
            get
            {
                return this.postDateField;
            }
            set
            {
                this.postDateField = value;
            }
        }

        /// <remarks/>
        public string OtherAmount
        {
            get
            {
                return this.otherAmountField;
            }
            set
            {
                this.otherAmountField = value;
            }
        }

        /// <remarks/>
        public string GiftDepositAvailable
        {
            get
            {
                return this.giftDepositAvailableField;
            }
            set
            {
                this.giftDepositAvailableField = value;
            }
        }

        /// <remarks/>
        public string SpecialPayment
        {
            get
            {
                return this.specialPaymentField;
            }
            set
            {
                this.specialPaymentField = value;
            }
        }

        /// <remarks/>
        public string WalletProviderID
        {
            get
            {
                return this.walletProviderIDField;
            }
            set
            {
                this.walletProviderIDField = value;
            }
        }

        /// <remarks/>
        public MasterPass MasterPass
        {
            get
            {
                return this.masterPassField;
            }
            set
            {
                this.masterPassField = value;
            }
        }

        /// <remarks/>
        public string FraudDetectInAuthTransId
        {
            get
            {
                return this.fraudDetectInAuthTransIdField;
            }
            set
            {
                this.fraudDetectInAuthTransIdField = value;
            }
        }

        /// <remarks/>
        public string SCV
        {
            get
            {
                return this.sCVField;
            }
            set
            {
                this.sCVField = value;
            }
        }

        /// <remarks/>
        public StoredCredentialsType StoredCredentials
        {
            get
            {
                return this.storedCredentialsField;
            }
            set
            {
                this.storedCredentialsField = value;
            }
        }

        /// <remarks/>
        public Extra_Type[] Extra
        {
            get
            {
                return this.extraField;
            }
            set
            {
                this.extraField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/encodedTypes")]
    public partial class Level3_Type
    {
        private string taxAmountField;

        private string taxRateField;

        private string altTaxAmountField;

        private string altTaxIdField;

        private string dutyAmountField;

        private string freightAmountField;

        private string discountAmountField;

        private string shipFromZipField;

        private Level3_ShipToAddress_Type shipToAddressField;

        private Level3_LineItem_Type[] lineItemField;

        /// <remarks/>
        public string TaxAmount
        {
            get
            {
                return this.taxAmountField;
            }
            set
            {
                this.taxAmountField = value;
            }
        }

        /// <remarks/>
        public string TaxRate
        {
            get
            {
                return this.taxRateField;
            }
            set
            {
                this.taxRateField = value;
            }
        }

        /// <remarks/>
        public string AltTaxAmount
        {
            get
            {
                return this.altTaxAmountField;
            }
            set
            {
                this.altTaxAmountField = value;
            }
        }

        /// <remarks/>
        public string AltTaxId
        {
            get
            {
                return this.altTaxIdField;
            }
            set
            {
                this.altTaxIdField = value;
            }
        }

        /// <remarks/>
        public string DutyAmount
        {
            get
            {
                return this.dutyAmountField;
            }
            set
            {
                this.dutyAmountField = value;
            }
        }

        /// <remarks/>
        public string FreightAmount
        {
            get
            {
                return this.freightAmountField;
            }
            set
            {
                this.freightAmountField = value;
            }
        }

        /// <remarks/>
        public string DiscountAmount
        {
            get
            {
                return this.discountAmountField;
            }
            set
            {
                this.discountAmountField = value;
            }
        }

        /// <remarks/>
        public string ShipFromZip
        {
            get
            {
                return this.shipFromZipField;
            }
            set
            {
                this.shipFromZipField = value;
            }
        }

        /// <remarks/>
        public Level3_ShipToAddress_Type ShipToAddress
        {
            get
            {
                return this.shipToAddressField;
            }
            set
            {
                this.shipToAddressField = value;
            }
        }

        /// <remarks/>
        public Level3_LineItem_Type[] LineItem
        {
            get
            {
                return this.lineItemField;
            }
            set
            {
                this.lineItemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/encodedTypes")]
    public partial class Level3_ShipToAddress_Type
    {

        private string address1Field;

        private string cityField;

        private string stateField;

        private string countryField;

        private string customerNumberField;

        private string emailField;

        private string phoneField;

        private string nameField;

        private string zipField;

        /// <remarks/>
        public string Address1
        {
            get
            {
                return this.address1Field;
            }
            set
            {
                this.address1Field = value;
            }
        }

        /// <remarks/>
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        /// <remarks/>
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }

        /// <remarks/>
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        /// <remarks/>
        public string CustomerNumber
        {
            get
            {
                return this.customerNumberField;
            }
            set
            {
                this.customerNumberField = value;
            }
        }

        /// <remarks/>
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }

        /// <remarks/>
        public string Phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string Zip
        {
            get
            {
                return this.zipField;
            }
            set
            {
                this.zipField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(CheckTransactionResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/encodedTypes")]
    public partial class CheckTransaction
    {

        private string exactIDField;

        private string passwordField;

        private string transaction_TypeField;

        private string dollarAmountField;

        private string checkTypeField;

        private string mICRField;

        private string checkNumberField;

        private string bankAccountNumberField;

        private string bankRoutingNumberField;

        private string transaction_TagField;

        private string splitTenderIDField;

        private string authorization_NumField;

        private string customerNameField;

        private string ecommerce_FlagField;

        private string reference_NoField;

        private string customer_RefField;

        private string languageField;

        private string client_IPField;

        private string client_EmailField;

        private string user_NameField;

        private string customerIDTypeField;

        private string customerIDField;

        private string releaseTypeField;

        private string giftCardAmountField;

        private string dateOfBirthField;

        private bool vIPField;

        private bool vIPFieldSpecified;

        private string registrationNoField;

        private string registrationDateField;

        private string clerkIDField;

        private string deviceIDField;

        private Address_Type addressField;

        private string tPPIDField;

        private string splitShipmentNumberField;

        private SoftDescriptor_Type softDescriptorField;

        /// <remarks/>
        public string ExactID
        {
            get
            {
                return this.exactIDField;
            }
            set
            {
                this.exactIDField = value;
            }
        }

        /// <remarks/>
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        public string Transaction_Type
        {
            get
            {
                return this.transaction_TypeField;
            }
            set
            {
                this.transaction_TypeField = value;
            }
        }

        /// <remarks/>
        public string DollarAmount
        {
            get
            {
                return this.dollarAmountField;
            }
            set
            {
                this.dollarAmountField = value;
            }
        }

        /// <remarks/>
        public string CheckType
        {
            get
            {
                return this.checkTypeField;
            }
            set
            {
                this.checkTypeField = value;
            }
        }

        /// <remarks/>
        public string MICR
        {
            get
            {
                return this.mICRField;
            }
            set
            {
                this.mICRField = value;
            }
        }

        /// <remarks/>
        public string CheckNumber
        {
            get
            {
                return this.checkNumberField;
            }
            set
            {
                this.checkNumberField = value;
            }
        }

        /// <remarks/>
        public string BankAccountNumber
        {
            get
            {
                return this.bankAccountNumberField;
            }
            set
            {
                this.bankAccountNumberField = value;
            }
        }

        /// <remarks/>
        public string BankRoutingNumber
        {
            get
            {
                return this.bankRoutingNumberField;
            }
            set
            {
                this.bankRoutingNumberField = value;
            }
        }

        /// <remarks/>
        public string Transaction_Tag
        {
            get
            {
                return this.transaction_TagField;
            }
            set
            {
                this.transaction_TagField = value;
            }
        }

        /// <remarks/>
        public string SplitTenderID
        {
            get
            {
                return this.splitTenderIDField;
            }
            set
            {
                this.splitTenderIDField = value;
            }
        }

        /// <remarks/>
        public string Authorization_Num
        {
            get
            {
                return this.authorization_NumField;
            }
            set
            {
                this.authorization_NumField = value;
            }
        }

        /// <remarks/>
        public string CustomerName
        {
            get
            {
                return this.customerNameField;
            }
            set
            {
                this.customerNameField = value;
            }
        }

        /// <remarks/>
        public string Ecommerce_Flag
        {
            get
            {
                return this.ecommerce_FlagField;
            }
            set
            {
                this.ecommerce_FlagField = value;
            }
        }

        /// <remarks/>
        public string Reference_No
        {
            get
            {
                return this.reference_NoField;
            }
            set
            {
                this.reference_NoField = value;
            }
        }

        /// <remarks/>
        public string Customer_Ref
        {
            get
            {
                return this.customer_RefField;
            }
            set
            {
                this.customer_RefField = value;
            }
        }

        /// <remarks/>
        public string Language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }

        /// <remarks/>
        public string Client_IP
        {
            get
            {
                return this.client_IPField;
            }
            set
            {
                this.client_IPField = value;
            }
        }

        /// <remarks/>
        public string Client_Email
        {
            get
            {
                return this.client_EmailField;
            }
            set
            {
                this.client_EmailField = value;
            }
        }

        /// <remarks/>
        public string User_Name
        {
            get
            {
                return this.user_NameField;
            }
            set
            {
                this.user_NameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string CustomerIDType
        {
            get
            {
                return this.customerIDTypeField;
            }
            set
            {
                this.customerIDTypeField = value;
            }
        }

        /// <remarks/>
        public string CustomerID
        {
            get
            {
                return this.customerIDField;
            }
            set
            {
                this.customerIDField = value;
            }
        }

        /// <remarks/>
        public string ReleaseType
        {
            get
            {
                return this.releaseTypeField;
            }
            set
            {
                this.releaseTypeField = value;
            }
        }

        /// <remarks/>
        public string GiftCardAmount
        {
            get
            {
                return this.giftCardAmountField;
            }
            set
            {
                this.giftCardAmountField = value;
            }
        }

        /// <remarks/>
        public string DateOfBirth
        {
            get
            {
                return this.dateOfBirthField;
            }
            set
            {
                this.dateOfBirthField = value;
            }
        }

        /// <remarks/>
        public bool VIP
        {
            get
            {
                return this.vIPField;
            }
            set
            {
                this.vIPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool VIPSpecified
        {
            get
            {
                return this.vIPFieldSpecified;
            }
            set
            {
                this.vIPFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string RegistrationNo
        {
            get
            {
                return this.registrationNoField;
            }
            set
            {
                this.registrationNoField = value;
            }
        }

        /// <remarks/>
        public string RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }

        /// <remarks/>
        public string ClerkID
        {
            get
            {
                return this.clerkIDField;
            }
            set
            {
                this.clerkIDField = value;
            }
        }

        /// <remarks/>
        public string DeviceID
        {
            get
            {
                return this.deviceIDField;
            }
            set
            {
                this.deviceIDField = value;
            }
        }

        /// <remarks/>
        public Address_Type Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        /// <remarks/>
        public string TPPID
        {
            get
            {
                return this.tPPIDField;
            }
            set
            {
                this.tPPIDField = value;
            }
        }

        /// <remarks/>
        public string SplitShipmentNumber
        {
            get
            {
                return this.splitShipmentNumberField;
            }
            set
            {
                this.splitShipmentNumberField = value;
            }
        }

        /// <remarks/>
        public SoftDescriptor_Type SoftDescriptor
        {
            get
            {
                return this.softDescriptorField;
            }
            set
            {
                this.softDescriptorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/encodedTypes")]
    public partial class Address_Type
    {

        private string address1Field;

        private string address2Field;

        private string cityField;

        private string stateField;

        private string zipField;

        private string countryCodeField;

        private string phoneNumberField;

        private string phoneTypeField;

        /// <remarks/>
        public string Address1
        {
            get
            {
                return this.address1Field;
            }
            set
            {
                this.address1Field = value;
            }
        }

        /// <remarks/>
        public string Address2
        {
            get
            {
                return this.address2Field;
            }
            set
            {
                this.address2Field = value;
            }
        }

        /// <remarks/>
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        /// <remarks/>
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }

        /// <remarks/>
        public string Zip
        {
            get
            {
                return this.zipField;
            }
            set
            {
                this.zipField = value;
            }
        }

        /// <remarks/>
        public string CountryCode
        {
            get
            {
                return this.countryCodeField;
            }
            set
            {
                this.countryCodeField = value;
            }
        }

        /// <remarks/>
        public string PhoneNumber
        {
            get
            {
                return this.phoneNumberField;
            }
            set
            {
                this.phoneNumberField = value;
            }
        }

        /// <remarks/>
        public string PhoneType
        {
            get
            {
                return this.phoneTypeField;
            }
            set
            {
                this.phoneTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/encodedTypes")]
    public partial class SoftDescriptor_Type
    {

        private string dBANameField;

        private string streetField;

        private string cityField;

        private string regionField;

        private string postalCodeField;

        private string countryCodeField;

        private string mIDField;

        private string mCCField;

        private string merchantContactInfoField;

        private string mVV_MAIDField;

        private string aMEXMerchantPhoneField;

        private string aMEXMerchantEmailField;

        private string pFacSubmerchantIdField;

        private string pFacNameField;

        /// <remarks/>
        public string DBAName
        {
            get
            {
                return this.dBANameField;
            }
            set
            {
                this.dBANameField = value;
            }
        }

        /// <remarks/>
        public string Street
        {
            get
            {
                return this.streetField;
            }
            set
            {
                this.streetField = value;
            }
        }

        /// <remarks/>
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        /// <remarks/>
        public string Region
        {
            get
            {
                return this.regionField;
            }
            set
            {
                this.regionField = value;
            }
        }

        /// <remarks/>
        public string PostalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }

        /// <remarks/>
        public string CountryCode
        {
            get
            {
                return this.countryCodeField;
            }
            set
            {
                this.countryCodeField = value;
            }
        }

        /// <remarks/>
        public string MID
        {
            get
            {
                return this.mIDField;
            }
            set
            {
                this.mIDField = value;
            }
        }

        /// <remarks/>
        public string MCC
        {
            get
            {
                return this.mCCField;
            }
            set
            {
                this.mCCField = value;
            }
        }

        /// <remarks/>
        public string MerchantContactInfo
        {
            get
            {
                return this.merchantContactInfoField;
            }
            set
            {
                this.merchantContactInfoField = value;
            }
        }

        /// <remarks/>
        public string MVV_MAID
        {
            get
            {
                return this.mVV_MAIDField;
            }
            set
            {
                this.mVV_MAIDField = value;
            }
        }

        /// <remarks/>
        public string AMEXMerchantPhone
        {
            get
            {
                return this.aMEXMerchantPhoneField;
            }
            set
            {
                this.aMEXMerchantPhoneField = value;
            }
        }

        /// <remarks/>
        public string AMEXMerchantEmail
        {
            get
            {
                return this.aMEXMerchantEmailField;
            }
            set
            {
                this.aMEXMerchantEmailField = value;
            }
        }

        /// <remarks/>
        public string PFacSubmerchantId
        {
            get
            {
                return this.pFacSubmerchantIdField;
            }
            set
            {
                this.pFacSubmerchantIdField = value;
            }
        }

        /// <remarks/>
        public string PFacName
        {
            get
            {
                return this.pFacNameField;
            }
            set
            {
                this.pFacNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/encodedTypes")]
    public partial class CheckTransactionResult : CheckTransaction
    {

        private bool transaction_ErrorField;

        private bool transaction_ApprovedField;

        private string eXact_Resp_CodeField;

        private string eXact_MessageField;

        private string bank_Resp_CodeField;

        private string bank_MessageField;

        private string bank_Resp_Code_2Field;

        private string sequenceNoField;

        private string merchantNameField;

        private string merchantAddressField;

        private string merchantCityField;

        private string merchantProvinceField;

        private string merchantCountryField;

        private string merchantPostalField;

        private string merchantURLField;

        private string cTRField;

        /// <remarks/>
        public bool Transaction_Error
        {
            get
            {
                return this.transaction_ErrorField;
            }
            set
            {
                this.transaction_ErrorField = value;
            }
        }

        /// <remarks/>
        public bool Transaction_Approved
        {
            get
            {
                return this.transaction_ApprovedField;
            }
            set
            {
                this.transaction_ApprovedField = value;
            }
        }

        /// <remarks/>
        public string EXact_Resp_Code
        {
            get
            {
                return this.eXact_Resp_CodeField;
            }
            set
            {
                this.eXact_Resp_CodeField = value;
            }
        }

        /// <remarks/>
        public string EXact_Message
        {
            get
            {
                return this.eXact_MessageField;
            }
            set
            {
                this.eXact_MessageField = value;
            }
        }

        /// <remarks/>
        public string Bank_Resp_Code
        {
            get
            {
                return this.bank_Resp_CodeField;
            }
            set
            {
                this.bank_Resp_CodeField = value;
            }
        }

        /// <remarks/>
        public string Bank_Message
        {
            get
            {
                return this.bank_MessageField;
            }
            set
            {
                this.bank_MessageField = value;
            }
        }

        /// <remarks/>
        public string Bank_Resp_Code_2
        {
            get
            {
                return this.bank_Resp_Code_2Field;
            }
            set
            {
                this.bank_Resp_Code_2Field = value;
            }
        }

        /// <remarks/>
        public string SequenceNo
        {
            get
            {
                return this.sequenceNoField;
            }
            set
            {
                this.sequenceNoField = value;
            }
        }

        /// <remarks/>
        public string MerchantName
        {
            get
            {
                return this.merchantNameField;
            }
            set
            {
                this.merchantNameField = value;
            }
        }

        /// <remarks/>
        public string MerchantAddress
        {
            get
            {
                return this.merchantAddressField;
            }
            set
            {
                this.merchantAddressField = value;
            }
        }

        /// <remarks/>
        public string MerchantCity
        {
            get
            {
                return this.merchantCityField;
            }
            set
            {
                this.merchantCityField = value;
            }
        }

        /// <remarks/>
        public string MerchantProvince
        {
            get
            {
                return this.merchantProvinceField;
            }
            set
            {
                this.merchantProvinceField = value;
            }
        }

        /// <remarks/>
        public string MerchantCountry
        {
            get
            {
                return this.merchantCountryField;
            }
            set
            {
                this.merchantCountryField = value;
            }
        }

        /// <remarks/>
        public string MerchantPostal
        {
            get
            {
                return this.merchantPostalField;
            }
            set
            {
                this.merchantPostalField = value;
            }
        }

        /// <remarks/>
        public string MerchantURL
        {
            get
            {
                return this.merchantURLField;
            }
            set
            {
                this.merchantURLField = value;
            }
        }

        /// <remarks/>
        public string CTR
        {
            get
            {
                return this.cTRField;
            }
            set
            {
                this.cTRField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/encodedTypes")]
    public partial class FraudDetectExplanation_Type
    {

        private string typeField;

        private string descriptionField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/encodedTypes")]
    public partial class FraudDetectResult
    {

        private string scoreField;

        private string recommendationField;

        private FraudDetectExplanation_Type[] explanationField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string Score
        {
            get
            {
                return this.scoreField;
            }
            set
            {
                this.scoreField = value;
            }
        }

        /// <remarks/>
        public string Recommendation
        {
            get
            {
                return this.recommendationField;
            }
            set
            {
                this.recommendationField = value;
            }
        }

        /// <remarks/>
        public FraudDetectExplanation_Type[] Explanation
        {
            get
            {
                return this.explanationField;
            }
            set
            {
                this.explanationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/encodedTypes")]
    public partial class ForeignCurrencyDetails
    {

        private string dCCIndicatorField;

        private string foreignAmountField;

        private string foreignCurrencyCodeField;

        private string exchangeRateField;

        private string marginRateField;

        private string rateSourceField;

        /// <remarks/>
        public string DCCIndicator
        {
            get
            {
                return this.dCCIndicatorField;
            }
            set
            {
                this.dCCIndicatorField = value;
            }
        }

        /// <remarks/>
        public string ForeignAmount
        {
            get
            {
                return this.foreignAmountField;
            }
            set
            {
                this.foreignAmountField = value;
            }
        }

        /// <remarks/>
        public string ForeignCurrencyCode
        {
            get
            {
                return this.foreignCurrencyCodeField;
            }
            set
            {
                this.foreignCurrencyCodeField = value;
            }
        }

        /// <remarks/>
        public string ExchangeRate
        {
            get
            {
                return this.exchangeRateField;
            }
            set
            {
                this.exchangeRateField = value;
            }
        }

        /// <remarks/>
        public string MarginRate
        {
            get
            {
                return this.marginRateField;
            }
            set
            {
                this.marginRateField = value;
            }
        }

        /// <remarks/>
        public string RateSource
        {
            get
            {
                return this.rateSourceField;
            }
            set
            {
                this.rateSourceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/encodedTypes")]
    public partial class Extra_Type
    {

        private string fieldField;

        private string valueField;

        /// <remarks/>
        public string Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }

        /// <remarks/>
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/encodedTypes")]
    public partial class StoredCredentialsType
    {

        private string authorizationTypeOverrideField;

        private string initiationField;

        private string indicatorField;

        private string protectbuyIndicatorField;

        private string scheduleField;

        private string transactionIdField;

        private string originalAmountField;

        /// <remarks/>
        public string AuthorizationTypeOverride
        {
            get
            {
                return this.authorizationTypeOverrideField;
            }
            set
            {
                this.authorizationTypeOverrideField = value;
            }
        }

        /// <remarks/>
        public string Initiation
        {
            get
            {
                return this.initiationField;
            }
            set
            {
                this.initiationField = value;
            }
        }

        /// <remarks/>
        public string Indicator
        {
            get
            {
                return this.indicatorField;
            }
            set
            {
                this.indicatorField = value;
            }
        }

        /// <remarks/>
        public string ProtectbuyIndicator
        {
            get
            {
                return this.protectbuyIndicatorField;
            }
            set
            {
                this.protectbuyIndicatorField = value;
            }
        }

        /// <remarks/>
        public string Schedule
        {
            get
            {
                return this.scheduleField;
            }
            set
            {
                this.scheduleField = value;
            }
        }

        /// <remarks/>
        public string TransactionId
        {
            get
            {
                return this.transactionIdField;
            }
            set
            {
                this.transactionIdField = value;
            }
        }

        /// <remarks/>
        public string OriginalAmount
        {
            get
            {
                return this.originalAmountField;
            }
            set
            {
                this.originalAmountField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/encodedTypes")]
    public partial class MasterPass
    {

        private string transactionIDField;

        private string walletIDField;

        private string indicatorField;

        /// <remarks/>
        public string TransactionID
        {
            get
            {
                return this.transactionIDField;
            }
            set
            {
                this.transactionIDField = value;
            }
        }

        /// <remarks/>
        public string WalletID
        {
            get
            {
                return this.walletIDField;
            }
            set
            {
                this.walletIDField = value;
            }
        }

        /// <remarks/>
        public string Indicator
        {
            get
            {
                return this.indicatorField;
            }
            set
            {
                this.indicatorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/encodedTypes")]
    public partial class VisaCheckout
    {

        private string callIDField;

        private string promoCodeField;

        /// <remarks/>
        public string CallID
        {
            get
            {
                return this.callIDField;
            }
            set
            {
                this.callIDField = value;
            }
        }

        /// <remarks/>
        public string PromoCode
        {
            get
            {
                return this.promoCodeField;
            }
            set
            {
                this.promoCodeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/encodedTypes")]
    public partial class DynamicPricing
    {

        private string optedInField;

        private string rateResponseSignatureField;

        /// <remarks/>
        public string OptedIn
        {
            get
            {
                return this.optedInField;
            }
            set
            {
                this.optedInField = value;
            }
        }

        /// <remarks/>
        public string RateResponseSignature
        {
            get
            {
                return this.rateResponseSignatureField;
            }
            set
            {
                this.rateResponseSignatureField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/encodedTypes")]
    public partial class DynamicCurrency
    {

        private string optedInField;

        private string rateResponseSignatureField;

        /// <remarks/>
        public string OptedIn
        {
            get
            {
                return this.optedInField;
            }
            set
            {
                this.optedInField = value;
            }
        }

        /// <remarks/>
        public string RateResponseSignature
        {
            get
            {
                return this.rateResponseSignatureField;
            }
            set
            {
                this.rateResponseSignatureField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/encodedTypes")]
    public partial class PaypalTransactionDetails
    {

        private string payerIDField;

        private string grossAmountCurrencyIDField;

        private bool successField;

        private string authorizationField;

        private string messageField;

        private string correlationIDField;

        private string timestampField;

        /// <remarks/>
        public string PayerID
        {
            get
            {
                return this.payerIDField;
            }
            set
            {
                this.payerIDField = value;
            }
        }

        /// <remarks/>
        public string GrossAmountCurrencyID
        {
            get
            {
                return this.grossAmountCurrencyIDField;
            }
            set
            {
                this.grossAmountCurrencyIDField = value;
            }
        }

        /// <remarks/>
        public bool Success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }

        /// <remarks/>
        public string Authorization
        {
            get
            {
                return this.authorizationField;
            }
            set
            {
                this.authorizationField = value;
            }
        }

        /// <remarks/>
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        public string CorrelationID
        {
            get
            {
                return this.correlationIDField;
            }
            set
            {
                this.correlationIDField = value;
            }
        }

        /// <remarks/>
        public string Timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/encodedTypes")]
    public partial class Level3_LineItem_Type
    {

        private string commodityCodeField;

        private string descriptionField;

        private string discountAmountField;

        private bool discountIndicatorField;

        private bool discountIndicatorFieldSpecified;

        private bool grossNetIndicatorField;

        private bool grossNetIndicatorFieldSpecified;

        private string lineItemTotalField;

        private string productCodeField;

        private string quantityField;

        private string taxAmountField;

        private string taxRateField;

        private string taxTypeField;

        private string unitCostField;

        private string unitOfMeasureField;

        /// <remarks/>
        public string CommodityCode
        {
            get
            {
                return this.commodityCodeField;
            }
            set
            {
                this.commodityCodeField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string DiscountAmount
        {
            get
            {
                return this.discountAmountField;
            }
            set
            {
                this.discountAmountField = value;
            }
        }

        /// <remarks/>
        public bool DiscountIndicator
        {
            get
            {
                return this.discountIndicatorField;
            }
            set
            {
                this.discountIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool DiscountIndicatorSpecified
        {
            get
            {
                return this.discountIndicatorFieldSpecified;
            }
            set
            {
                this.discountIndicatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool GrossNetIndicator
        {
            get
            {
                return this.grossNetIndicatorField;
            }
            set
            {
                this.grossNetIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool GrossNetIndicatorSpecified
        {
            get
            {
                return this.grossNetIndicatorFieldSpecified;
            }
            set
            {
                this.grossNetIndicatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string LineItemTotal
        {
            get
            {
                return this.lineItemTotalField;
            }
            set
            {
                this.lineItemTotalField = value;
            }
        }

        /// <remarks/>
        public string ProductCode
        {
            get
            {
                return this.productCodeField;
            }
            set
            {
                this.productCodeField = value;
            }
        }

        /// <remarks/>
        public string Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }

        /// <remarks/>
        public string TaxAmount
        {
            get
            {
                return this.taxAmountField;
            }
            set
            {
                this.taxAmountField = value;
            }
        }

        /// <remarks/>
        public string TaxRate
        {
            get
            {
                return this.taxRateField;
            }
            set
            {
                this.taxRateField = value;
            }
        }

        /// <remarks/>
        public string TaxType
        {
            get
            {
                return this.taxTypeField;
            }
            set
            {
                this.taxTypeField = value;
            }
        }

        /// <remarks/>
        public string UnitCost
        {
            get
            {
                return this.unitCostField;
            }
            set
            {
                this.unitCostField = value;
            }
        }

        /// <remarks/>
        public string UnitOfMeasure
        {
            get
            {
                return this.unitOfMeasureField;
            }
            set
            {
                this.unitOfMeasureField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/encodedTypes")]
    public partial class TransactionResult : Transaction
    {

        private bool transaction_ErrorField;

        private bool transaction_ApprovedField;

        private string eXact_Resp_CodeField;

        private string eXact_MessageField;

        private string bank_Resp_CodeField;

        private string bank_MessageField;

        private string bank_Resp_Code_2Field;

        private string sequenceNoField;

        private string aVSField;

        private string cVV2Field;

        private string retrieval_Ref_NoField;

        private string cAVV_ResponseField;

        private string amountRequestedField;

        private string merchantNameField;

        private string merchantAddressField;

        private string merchantCityField;

        private string merchantProvinceField;

        private string merchantCountryField;

        private string merchantPostalField;

        private string merchantURLField;

        private string currentBalanceField;

        private string previousBalanceField;

        private ForeignCurrencyDetails foreignCurrencyDetailsField;

        private FraudDetectResult fraudDetectField;

        private string cTRField;

        private string valueLinkAuthCodeField;

        private string localCurrencyCodeField;

        private string promoDetailsField;

        /// <remarks/>
        public bool Transaction_Error
        {
            get
            {
                return this.transaction_ErrorField;
            }
            set
            {
                this.transaction_ErrorField = value;
            }
        }

        /// <remarks/>
        public bool Transaction_Approved
        {
            get
            {
                return this.transaction_ApprovedField;
            }
            set
            {
                this.transaction_ApprovedField = value;
            }
        }

        /// <remarks/>
        public string EXact_Resp_Code
        {
            get
            {
                return this.eXact_Resp_CodeField;
            }
            set
            {
                this.eXact_Resp_CodeField = value;
            }
        }

        /// <remarks/>
        public string EXact_Message
        {
            get
            {
                return this.eXact_MessageField;
            }
            set
            {
                this.eXact_MessageField = value;
            }
        }

        /// <remarks/>
        public string Bank_Resp_Code
        {
            get
            {
                return this.bank_Resp_CodeField;
            }
            set
            {
                this.bank_Resp_CodeField = value;
            }
        }

        /// <remarks/>
        public string Bank_Message
        {
            get
            {
                return this.bank_MessageField;
            }
            set
            {
                this.bank_MessageField = value;
            }
        }

        /// <remarks/>
        public string Bank_Resp_Code_2
        {
            get
            {
                return this.bank_Resp_Code_2Field;
            }
            set
            {
                this.bank_Resp_Code_2Field = value;
            }
        }

        /// <remarks/>
        public string SequenceNo
        {
            get
            {
                return this.sequenceNoField;
            }
            set
            {
                this.sequenceNoField = value;
            }
        }

        /// <remarks/>
        public string AVS
        {
            get
            {
                return this.aVSField;
            }
            set
            {
                this.aVSField = value;
            }
        }

        /// <remarks/>
        public string CVV2
        {
            get
            {
                return this.cVV2Field;
            }
            set
            {
                this.cVV2Field = value;
            }
        }

        /// <remarks/>
        public string Retrieval_Ref_No
        {
            get
            {
                return this.retrieval_Ref_NoField;
            }
            set
            {
                this.retrieval_Ref_NoField = value;
            }
        }

        /// <remarks/>
        public string CAVV_Response
        {
            get
            {
                return this.cAVV_ResponseField;
            }
            set
            {
                this.cAVV_ResponseField = value;
            }
        }

        /// <remarks/>
        public string AmountRequested
        {
            get
            {
                return this.amountRequestedField;
            }
            set
            {
                this.amountRequestedField = value;
            }
        }

        /// <remarks/>
        public string MerchantName
        {
            get
            {
                return this.merchantNameField;
            }
            set
            {
                this.merchantNameField = value;
            }
        }

        /// <remarks/>
        public string MerchantAddress
        {
            get
            {
                return this.merchantAddressField;
            }
            set
            {
                this.merchantAddressField = value;
            }
        }

        /// <remarks/>
        public string MerchantCity
        {
            get
            {
                return this.merchantCityField;
            }
            set
            {
                this.merchantCityField = value;
            }
        }

        /// <remarks/>
        public string MerchantProvince
        {
            get
            {
                return this.merchantProvinceField;
            }
            set
            {
                this.merchantProvinceField = value;
            }
        }

        /// <remarks/>
        public string MerchantCountry
        {
            get
            {
                return this.merchantCountryField;
            }
            set
            {
                this.merchantCountryField = value;
            }
        }

        /// <remarks/>
        public string MerchantPostal
        {
            get
            {
                return this.merchantPostalField;
            }
            set
            {
                this.merchantPostalField = value;
            }
        }

        /// <remarks/>
        public string MerchantURL
        {
            get
            {
                return this.merchantURLField;
            }
            set
            {
                this.merchantURLField = value;
            }
        }

        /// <remarks/>
        public string CurrentBalance
        {
            get
            {
                return this.currentBalanceField;
            }
            set
            {
                this.currentBalanceField = value;
            }
        }

        /// <remarks/>
        public string PreviousBalance
        {
            get
            {
                return this.previousBalanceField;
            }
            set
            {
                this.previousBalanceField = value;
            }
        }

        /// <remarks/>
        public ForeignCurrencyDetails ForeignCurrencyDetails
        {
            get
            {
                return this.foreignCurrencyDetailsField;
            }
            set
            {
                this.foreignCurrencyDetailsField = value;
            }
        }

        /// <remarks/>
        public FraudDetectResult FraudDetect
        {
            get
            {
                return this.fraudDetectField;
            }
            set
            {
                this.fraudDetectField = value;
            }
        }

        /// <remarks/>
        public string CTR
        {
            get
            {
                return this.cTRField;
            }
            set
            {
                this.cTRField = value;
            }
        }

        /// <remarks/>
        public string ValueLinkAuthCode
        {
            get
            {
                return this.valueLinkAuthCodeField;
            }
            set
            {
                this.valueLinkAuthCodeField = value;
            }
        }

        /// <remarks/>
        public string LocalCurrencyCode
        {
            get
            {
                return this.localCurrencyCodeField;
            }
            set
            {
                this.localCurrencyCodeField = value;
            }
        }

        /// <remarks/>
        public string PromoDetails
        {
            get
            {
                return this.promoDetailsField;
            }
            set
            {
                this.promoDetailsField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendAndCommit", WrapperNamespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/Request", IsWrapped=true)]
    public partial class SendAndCommitRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public E4.Transaction SendAndCommitSource;

        public SendAndCommitRequest()
        {
        }

        public SendAndCommitRequest(E4.Transaction SendAndCommitSource)
        {
            this.SendAndCommitSource = SendAndCommitSource;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendAndCommitResponse", WrapperNamespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/Response", IsWrapped=true)]
    public partial class SendAndCommitResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public E4.TransactionResult SendAndCommitResult;

        public SendAndCommitResponse()
        {
        }

        public SendAndCommitResponse(E4.TransactionResult SendAndCommitResult)
        {
            this.SendAndCommitResult = SendAndCommitResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendAndCommitCheck", WrapperNamespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/Request", IsWrapped=true)]
    public partial class SendAndCommitCheckRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public E4.CheckTransaction SendAndCommitCheckSource;

        public SendAndCommitCheckRequest()
        {
        }

        public SendAndCommitCheckRequest(E4.CheckTransaction SendAndCommitCheckSource)
        {
            this.SendAndCommitCheckSource = SendAndCommitCheckSource;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendAndCommitCheckResponse", WrapperNamespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/Response", IsWrapped=true)]
    public partial class SendAndCommitCheckResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public E4.CheckTransactionResult SendAndCommitCheckResult;

        public SendAndCommitCheckResponse()
        {
        }

        public SendAndCommitCheckResponse(E4.CheckTransactionResult SendAndCommitCheckResult)
        {
            this.SendAndCommitCheckResult = SendAndCommitCheckResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TransactionInfo", WrapperNamespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/Request", IsWrapped=true)]
    public partial class TransactionInfoRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public E4.Transaction TransactionInfoSource;

        public TransactionInfoRequest()
        {
        }

        public TransactionInfoRequest(E4.Transaction TransactionInfoSource)
        {
            this.TransactionInfoSource = TransactionInfoSource;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TransactionInfoResponse", WrapperNamespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/Response", IsWrapped=true)]
    public partial class TransactionInfoResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public E4.TransactionResult TransactionInfoResult;

        public TransactionInfoResponse()
        {
        }

        public TransactionInfoResponse(E4.TransactionResult TransactionInfoResult)
        {
            this.TransactionInfoResult = TransactionInfoResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckTransactionInfo", WrapperNamespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/Request", IsWrapped=true)]
    public partial class CheckTransactionInfoRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public E4.CheckTransaction CheckTransactionInfoSource;

        public CheckTransactionInfoRequest()
        {
        }

        public CheckTransactionInfoRequest(E4.CheckTransaction CheckTransactionInfoSource)
        {
            this.CheckTransactionInfoSource = CheckTransactionInfoSource;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckTransactionInfoResponse", WrapperNamespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/Response", IsWrapped=true)]
    public partial class CheckTransactionInfoResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public E4.CheckTransactionResult CheckTransactionInfoResult;

        public CheckTransactionInfoResponse()
        {
        }

        public CheckTransactionInfoResponse(E4.CheckTransactionResult CheckTransactionInfoResult)
        {
            this.CheckTransactionInfoResult = CheckTransactionInfoResult;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ServiceSoapChannel : E4.ServiceSoap, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<E4.ServiceSoap>, E4.ServiceSoap
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public ServiceSoapClient(string endpointConfigurationName) :
                base(endpointConfigurationName){
        }

        public ServiceSoapClient() :
                base(ServiceSoapClient.GetDefaultBinding(), ServiceSoapClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ServiceSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public ServiceSoapClient(EndpointConfiguration endpointConfiguration) :
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<E4.SendAndCommitResponse> E4.ServiceSoap.SendAndCommitAsync(E4.SendAndCommitRequest request)
        {
            return base.Channel.SendAndCommitAsync(request);
        }

        public System.Threading.Tasks.Task<E4.SendAndCommitResponse> SendAndCommitAsync(E4.Transaction SendAndCommitSource)
        {
            E4.SendAndCommitRequest inValue = new E4.SendAndCommitRequest();
            inValue.SendAndCommitSource = SendAndCommitSource;
            return ((E4.ServiceSoap)(this)).SendAndCommitAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<E4.SendAndCommitCheckResponse> E4.ServiceSoap.SendAndCommitCheckAsync(E4.SendAndCommitCheckRequest request)
        {
            return base.Channel.SendAndCommitCheckAsync(request);
        }

        public System.Threading.Tasks.Task<E4.SendAndCommitCheckResponse> SendAndCommitCheckAsync(E4.CheckTransaction SendAndCommitCheckSource)
        {
            E4.SendAndCommitCheckRequest inValue = new E4.SendAndCommitCheckRequest();
            inValue.SendAndCommitCheckSource = SendAndCommitCheckSource;
            return ((E4.ServiceSoap)(this)).SendAndCommitCheckAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<E4.TransactionInfoResponse> E4.ServiceSoap.TransactionInfoAsync(E4.TransactionInfoRequest request)
        {
            return base.Channel.TransactionInfoAsync(request);
        }

        public System.Threading.Tasks.Task<E4.TransactionInfoResponse> TransactionInfoAsync(E4.Transaction TransactionInfoSource)
        {
            E4.TransactionInfoRequest inValue = new E4.TransactionInfoRequest();
            inValue.TransactionInfoSource = TransactionInfoSource;
            return ((E4.ServiceSoap)(this)).TransactionInfoAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<E4.CheckTransactionInfoResponse> E4.ServiceSoap.CheckTransactionInfoAsync(E4.CheckTransactionInfoRequest request)
        {
            return base.Channel.CheckTransactionInfoAsync(request);
        }

        public System.Threading.Tasks.Task<E4.CheckTransactionInfoResponse> CheckTransactionInfoAsync(E4.CheckTransaction CheckTransactionInfoSource)
        {
            E4.CheckTransactionInfoRequest inValue = new E4.CheckTransactionInfoRequest();
            inValue.CheckTransactionInfoSource = CheckTransactionInfoSource;
            return ((E4.ServiceSoap)(this)).CheckTransactionInfoAsync(inValue);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://api.globalgatewaye4.firstdata.com/transaction/v29");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceSoapClient.GetBindingForEndpoint(EndpointConfiguration.ServiceSoap);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceSoapClient.GetEndpointAddress(EndpointConfiguration.ServiceSoap);
        }

        public enum EndpointConfiguration
        {

            ServiceSoap,
        }
    }
}
